name: bpwave2-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py311h313beb8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - libcxx=17.0.6=he5c5206_4
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.18=h27ca646_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.1=h81ee809_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py311h80987f9_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h19e8193_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=26.2.0=py311h313beb8_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py311hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h6ba3021_1
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - pip:
      - attrs==25.4.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - fonttools==4.58.5
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - nbformat==5.10.4
      - numpy==2.3.1
      - openpyxl==3.1.5
      - pandas==2.3.1
      - patsy==1.0.2
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - referencing==0.37.0
      - rpds-py==0.28.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - snakeviz==2.2.2
      - statsmodels==0.14.5
      - tzdata==2025.2
prefix: /Users/guillers/anaconda3/envs/bpwave2-env
